# Generated by Django 3.2.5 on 2021-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
